### ISSUE TITLE
playlists mit nicht existierenden videos

### ISSUE THREAD

**Issue by jemand771** [jemand771/int-youtube-stat#13]
aktuelles verhalten:
wenn man eine playlist mit gelöschten oder privaten (?) videos drin lädt, bekommt man als fehler "video nicht gefunden"

das sollte nicht so sein - stattdessen einfach die nicht verfügbaren videos ignorieren?

**Comment by TheColin21** [comment]
Reminder to self: test für dieses Verhalten
